// Skills offered as suggestions in the skills input: [name, category, aliases].
// Roughly ordered by popularity within each group; earlier entries win ties.
const SKILL_CATALOG = [
  // Languages
  ["JavaScript", "Language", ["js", "ecmascript"]],
  ["TypeScript", "Language", ["ts"]],
  ["Python", "Language", ["py"]],
  ["Java", "Language"],
  ["C", "Language"],
  ["C++", "Language", ["cpp", "cplusplus"]],
  ["C#", "Language", ["csharp", "c sharp"]],
  ["Go", "Language", ["golang"]],
  ["Rust", "Language"],
  ["Kotlin", "Language"],
  ["Swift", "Language"],
  ["Dart", "Language"],
  ["PHP", "Language"],
  ["Ruby", "Language"],
  ["Scala", "Language"],
  ["R", "Language"],
  ["MATLAB", "Language"],
  ["Julia", "Language"],
  ["Lua", "Language"],
  ["Perl", "Language"],
  ["Haskell", "Language"],
  ["Elixir", "Language"],
  ["Erlang", "Language"],
  ["Clojure", "Language"],
  ["F#", "Language", ["fsharp"]],
  ["Objective-C", "Language", ["objc"]],
  ["Zig", "Language"],
  ["Solidity", "Language"],
  ["Assembly", "Language", ["asm"]],
  ["SQL", "Language"],
  ["Bash", "Language", ["shell scripting"]],
  ["Shell", "Language", ["sh", "zsh"]],
  ["PowerShell", "Language"],
  ["HTML", "Language", ["html5"]],
  ["CSS", "Language", ["css3"]],
  ["Sass", "Language", ["scss"]],
  ["GraphQL", "Language", ["gql"]],
  ["WebAssembly", "Language", ["wasm"]],
  ["Verilog", "Language"],
  ["VHDL", "Language"],

  // Frontend frameworks and libraries
  ["React", "Framework", ["reactjs", "react.js"]],
  ["Next.js", "Framework", ["nextjs", "next"]],
  ["Vue.js", "Framework", ["vue", "vuejs"]],
  ["Nuxt", "Framework", ["nuxtjs", "nuxt.js"]],
  ["Angular", "Framework", ["angularjs"]],
  ["Svelte", "Framework"],
  ["SvelteKit", "Framework"],
  ["SolidJS", "Framework", ["solid"]],
  ["Astro", "Framework"],
  ["Remix", "Framework"],
  ["Gatsby", "Framework"],
  ["jQuery", "Library"],
  ["Redux", "Library"],
  ["Zustand", "Library"],
  ["TanStack Query", "Library", ["react query"]],
  ["Tailwind CSS", "Framework", ["tailwind", "tailwindcss"]],
  ["Bootstrap", "Framework"],
  ["Material UI", "Library", ["mui"]],
  ["shadcn/ui", "Library", ["shadcn"]],
  ["Chakra UI", "Library"],
  ["Three.js", "Library", ["threejs"]],
  ["D3.js", "Library", ["d3"]],
  ["Framer Motion", "Library"],
  ["GSAP", "Library"],
  ["Vite", "Tool"],
  ["Webpack", "Tool"],
  ["Babel", "Tool"],
  ["esbuild", "Tool"],

  // Backend frameworks
  ["Node.js", "Platform", ["node", "nodejs"]],
  ["Deno", "Platform"],
  ["Bun", "Platform"],
  ["Express", "Framework", ["expressjs", "express.js"]],
  ["NestJS", "Framework", ["nest"]],
  ["Fastify", "Framework"],
  ["Hono", "Framework"],
  ["Django", "Framework"],
  ["Flask", "Framework"],
  ["FastAPI", "Framework"],
  ["Spring Boot", "Framework", ["spring"]],
  ["Ruby on Rails", "Framework", ["rails", "ror"]],
  ["Laravel", "Framework"],
  ["ASP.NET", "Framework", ["asp.net core", "aspnet"]],
  [".NET", "Platform", ["dotnet"]],
  ["Gin", "Framework"],
  ["Actix", "Framework"],
  ["Axum", "Framework"],
  ["Phoenix", "Framework"],
  ["gRPC", "Tool"],
  ["REST APIs", "Concept", ["rest", "restful"]],
  ["WebSockets", "Concept", ["websocket"]],
  ["tRPC", "Library"],
  ["Prisma", "Library"],
  ["Drizzle", "Library"],
  ["Socket.IO", "Library", ["socketio"]],

  // Mobile and desktop
  ["Android", "Platform"],
  ["iOS", "Platform"],
  ["Jetpack Compose", "Framework", ["compose"]],
  ["SwiftUI", "Framework"],
  ["UIKit", "Framework"],
  ["Flutter", "Framework"],
  ["React Native", "Framework", ["rn"]],
  ["Expo", "Tool"],
  ["Ionic", "Framework"],
  ["Electron", "Framework"],
  ["Tauri", "Framework"],
  ["Qt", "Framework"],
  ["Chrome Extensions", "Platform", ["chrome extension"]],
  ["VS Code Extensions", "Platform", ["vscode extension"]],

  // Data, AI and ML
  ["Machine Learning", "Concept", ["ml"]],
  ["Deep Learning", "Concept", ["dl"]],
  ["Natural Language Processing", "Concept", ["nlp"]],
  ["Computer Vision", "Concept", ["cv"]],
  ["LLMs", "Concept", ["llm", "large language models"]],
  ["Generative AI", "Concept", ["genai", "gen ai"]],
  ["Prompt Engineering", "Concept"],
  ["RAG", "Concept", ["retrieval augmented generation"]],
  ["PyTorch", "Library", ["torch"]],
  ["TensorFlow", "Library", ["tf"]],
  ["Keras", "Library"],
  ["scikit-learn", "Library", ["sklearn"]],
  ["Hugging Face", "Platform", ["huggingface", "transformers"]],
  ["LangChain", "Library"],
  ["LlamaIndex", "Library"],
  ["OpenAI API", "Platform", ["openai"]],
  ["Anthropic API", "Platform", ["claude api", "anthropic"]],
  ["Ollama", "Tool"],
  ["NumPy", "Library"],
  ["pandas", "Library"],
  ["Matplotlib", "Library"],
  ["Jupyter", "Tool", ["jupyter notebook"]],
  ["OpenCV", "Library"],
  ["MediaPipe", "Library"],
  ["Apache Spark", "Platform", ["spark", "pyspark"]],
  ["Apache Kafka", "Platform", ["kafka"]],
  ["Airflow", "Tool"],
  ["dbt", "Tool"],
  ["Tableau", "Tool"],
  ["Power BI", "Tool"],
  ["Excel", "Tool"],
  ["Data Analysis", "Concept"],
  ["Data Visualization", "Concept"],

  // Databases
  ["PostgreSQL", "Database", ["postgres", "psql"]],
  ["MySQL", "Database"],
  ["SQLite", "Database"],
  ["MongoDB", "Database", ["mongo"]],
  ["Redis", "Database"],
  ["Firebase", "Platform"],
  ["Supabase", "Platform"],
  ["DynamoDB", "Database"],
  ["Cassandra", "Database"],
  ["Elasticsearch", "Database", ["elastic"]],
  ["Microsoft SQL Server", "Database", ["mssql", "sql server"]],
  ["Oracle Database", "Database", ["oracle"]],
  ["Neo4j", "Database"],
  ["Pinecone", "Database"],
  ["Cloudflare D1", "Database", ["d1"]],

  // Cloud and DevOps
  ["AWS", "Cloud", ["amazon web services"]],
  ["Google Cloud", "Cloud", ["gcp"]],
  ["Microsoft Azure", "Cloud", ["azure"]],
  ["Cloudflare", "Cloud"],
  ["Cloudflare Workers", "Cloud", ["workers"]],
  ["Vercel", "Cloud"],
  ["Netlify", "Cloud"],
  ["Heroku", "Cloud"],
  ["DigitalOcean", "Cloud"],
  ["Docker", "Tool"],
  ["Kubernetes", "Tool", ["k8s"]],
  ["Terraform", "Tool"],
  ["Ansible", "Tool"],
  ["Jenkins", "Tool"],
  ["GitHub Actions", "Tool"],
  ["GitLab CI", "Tool"],
  ["CI/CD", "Concept", ["cicd"]],
  ["Nginx", "Tool"],
  ["Linux", "Platform"],
  ["Serverless", "Concept"],
  ["Microservices", "Concept"],
  ["Prometheus", "Tool"],
  ["Grafana", "Tool"],

  // Tools and practices
  ["Git", "Tool"],
  ["GitHub", "Tool"],
  ["GitLab", "Tool"],
  ["Postman", "Tool"],
  ["Figma", "Tool"],
  ["Jira", "Tool"],
  ["Notion", "Tool"],
  ["Jest", "Tool"],
  ["Vitest", "Tool"],
  ["Playwright", "Tool"],
  ["Cypress", "Tool"],
  ["Selenium", "Tool"],
  ["pytest", "Tool"],
  ["JUnit", "Tool"],
  ["ESLint", "Tool"],
  ["Prettier", "Tool"],
  ["npm", "Tool"],
  ["Unity", "Platform"],
  ["Unreal Engine", "Platform", ["unreal"]],
  ["Godot", "Platform"],
  ["Blender", "Tool"],
  ["Arduino", "Platform"],
  ["Raspberry Pi", "Platform"],
  ["Ethereum", "Platform"],
  ["Web3", "Concept"],
  ["Data Structures & Algorithms", "Concept", ["dsa", "data structures", "algorithms"]],
  ["System Design", "Concept"],
  ["Object-Oriented Programming", "Concept", ["oop"]],
  ["Agile", "Concept", ["scrum"]],
  ["Test-Driven Development", "Concept", ["tdd"]],
  ["Unit Testing", "Concept"],
  ["Accessibility", "Concept", ["a11y", "wcag"]],
  ["SEO", "Concept"],
  ["UI/UX Design", "Concept", ["ui", "ux", "ui design", "ux design"]],
  ["Responsive Design", "Concept"],
  ["Web Performance", "Concept"],
  ["Cybersecurity", "Concept", ["security"]],
  ["OAuth", "Concept", ["oauth2"]],
  ["Authentication", "Concept", ["auth"]],
];
